version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html   # Destination directory on EC2 instance
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
